### ISSUE TITLE
artists are note accepted as argument as doc shows.

### ISSUE THREAD

**Issue by helixphoenix** [conradludgate/terraform-provider-spotify#35] opened 2021-11-13 11:29 UTC
│ Error: Unsupported argument
│ 
│   on main.tf line 19, in data "spotify_search_track" "by_artist":
│   19:   artists = ["Koop","Living Light","Wildlight","Ayla Nereo"]
│ 
│ An argument named "artists" is not expected here. Did you mean "artist"?

**Comment by helixphoenix** [comment] 2021-11-13 11:29
It works with artist

**Comment by helixphoenix** [comment] 2021-11-13 11:29
and its only string not list

**Comment by helixphoenix** [comment] 2021-11-13 11:29
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 19, in data "spotify_search_track" "by_artist":
│   19:   artist = ["Koop","Living Light","Wildlight","Ayla Nereo"]
│ 
│ Inappropriate value for attribute "artist": string required.

**Comment by helixphoenix** [comment] 2021-11-13 11:33
you need add each artist with different name 

data "spotify_search_track" "koop" {
  artist = "Koop"

}
data "spotify_search_track" "oak" {
  artist = "I Am Oak"

}

**Comment by conradludgate** [comment] 2021-11-13 11:49
Thanks for pointing this out. Yeah it was a change I had to make due to a bug, but I guess I forgot to update the docs

**Comment by conradludgate** [comment] 2021-11-13 11:50
It being a string and not a list is expected behaviour, I'll close this once I've updated the docs

**Closed** 2021-11-13 15:12 UTC
